services:
  db:
    image: postgres:18-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-maileroo}
      POSTGRES_PASSWORD: ${DB_PASS:-maileroo_pass}
      POSTGRES_DB: ${DB_NAME:-maileroo}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
